"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 20:41:53.232922
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoteles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('sedes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('tratamientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('viajes', sa.SmallInteger(), nullable=False),
    sa.Column('arcos', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("moneda IN ('USD', 'CRC')", name='ck_tratamientos_moneda'),
    sa.CheckConstraint('arcos IS NULL OR arcos IN (1, 2)', name='ck_tratamientos_arcos'),
    sa.CheckConstraint('precio >= 0', name='ck_tratamientos_precio'),
    sa.CheckConstraint('viajes IN (1, 2)', name='ck_tratamientos_viajes'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('vuelos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('destino', sa.String(length=20), nullable=False),
    sa.Column('clave_origen', sa.String(length=20), nullable=False),
    sa.Column('clave_destino', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.CheckConstraint("moneda IN ('USD', 'CRC')", name='ck_vuelos_moneda'),
    sa.CheckConstraint("tipo IN ('internacional', 'nacional')", name='ck_vuelos_tipo'),
    sa.CheckConstraint('precio IS NULL OR precio >= 0', name='ck_vuelos_precio'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_origen', 'clave_destino', name='uq_vuelos_ruta')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('pais', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('sede_id', sa.String(length=64), nullable=False),
    sa.Column('tratamiento', sa.String(length=80), nullable=False),
    sa.Column('arcos', sa.SmallInteger(), nullable=True),
    sa.Column('etapa_manual', sa.String(length=20), nullable=True),
    sa.Column('llegada_ruta', sa.String(length=30), nullable=False),
    sa.Column('llegada_fecha', sa.DateTime(), nullable=True),
    sa.Column('vuelo_nacional', sa.Boolean(), nullable=False),
    sa.Column('nacional_ida_ruta', sa.String(length=30), nullable=False),
    sa.Column('nacional_ida_fecha', sa.DateTime(), nullable=True),
    sa.Column('pickup_fecha', sa.DateTime(), nullable=True),
    sa.Column('hotel_nombre', sa.String(length=80), nullable=False),
    sa.Column('hotel_checkin', sa.Date(), nullable=True),
    sa.Column('hotel_checkout', sa.Date(), nullable=True),
    sa.Column('nacional_regreso_ruta', sa.String(length=30), nullable=False),
    sa.Column('nacional_regreso_fecha', sa.DateTime(), nullable=True),
    sa.Column('salida_ruta', sa.String(length=30), nullable=False),
    sa.Column('salida_fecha', sa.DateTime(), nullable=True),
    sa.Column('pagos_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pagos_viajes', sa.SmallInteger(), nullable=False),
    sa.Column('viaje1_monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('viaje1_estado', sa.String(length=10), nullable=False),
    sa.Column('viaje2_monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('viaje2_estado', sa.String(length=10), nullable=False),
    sa.Column('seguro_aseguradora', sa.String(length=60), nullable=False),
    sa.Column('seguro_poliza', sa.String(length=40), nullable=False),
    sa.Column('seguro_estado', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('arcos IS NULL OR arcos IN (1, 2)', name='ck_pacientes_arcos'),
    sa.CheckConstraint('pagos_total >= 0 AND viaje1_monto >= 0 AND viaje2_monto >= 0', name='ck_pacientes_montos'),
    sa.CheckConstraint('pagos_viajes IN (1, 2)', name='ck_pacientes_viajes'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_llegada_fecha'), 'pacientes', ['llegada_fecha'], unique=False)
    op.create_index(op.f('ix_pacientes_sede_id'), 'pacientes', ['sede_id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('autor_sub', sa.String(length=120), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_paciente_id'), 'comentarios', ['paciente_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documentos_paciente_id'), 'documentos', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_paciente_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_comentarios_paciente_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_pacientes_sede_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_llegada_fecha'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('vuelos')
    op.drop_table('tratamientos')
    op.drop_table('sedes')
    op.drop_table('hoteles')
    # ### end Alembic commands ###
