"""numero de vuelo y estados

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 21:12:58.610946
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_vuelo',
    sa.Column('vuelo', sa.String(length=10), nullable=False),
    sa.Column('encontrado', sa.Boolean(), nullable=False),
    sa.Column('datos', sa.Text(), nullable=False),
    sa.Column('consultado_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vuelo')
    )
    op.add_column('pacientes', sa.Column('llegada_vuelo', sa.String(length=10), server_default='', nullable=False))
    op.add_column('pacientes', sa.Column('nacional_ida_vuelo', sa.String(length=10), server_default='', nullable=False))
    op.add_column('pacientes', sa.Column('nacional_regreso_vuelo', sa.String(length=10), server_default='', nullable=False))
    op.add_column('pacientes', sa.Column('salida_vuelo', sa.String(length=10), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'salida_vuelo')
    op.drop_column('pacientes', 'nacional_regreso_vuelo')
    op.drop_column('pacientes', 'nacional_ida_vuelo')
    op.drop_column('pacientes', 'llegada_vuelo')
    op.drop_table('estados_vuelo')
    # ### end Alembic commands ###
